### ISSUE TITLE
Plugin hasn't been updated yet

### ISSUE THREAD

**Issue by jaapmarcus** [jakobbouchard/hestia-nginx-cache#10]
Probally due to the fact the stable version is still 2.1.0

readme.txt
Stable tag: 2.1.0

https://github.com/jakobbouchard/hestia-nginx-cache/blob/9965eae9009ecd1ce32897380fdc49422ee24b0b/hestia-nginx-cache.php#L14

https://github.com/jakobbouchard/hestia-nginx-cache/blob/9965eae9009ecd1ce32897380fdc49422ee24b0b/hestia-nginx-cache.php#L31

**Comment by imjuniper** [comment]
Ah damn yeah, I'll have to fix this. I'll bump it to 2.1.2

**Comment by imjuniper** [comment]
It's done and updated! 👍
