### ISSUE TITLE
Frontend admin bar button not showing

### ISSUE THREAD

**Issue by chriscapisce** [jakobbouchard/hestia-nginx-cache#14]
The frontend admin bar button is not showing in any of my installations. 
Would you be able to implement it? Thanks in advance.

**Comment by imjuniper** [comment]
Sorry I completely forgot about this issue since I started university 😅 is it still a problem? By default it is disabled, but you can enable it by going into Settings > Hestia Nginx Cache and checking the box labeled _Show button in the admin bar_. If that doesn't work, let me know!

**Comment by chriscapisce** [comment]
Unfortunately, that doesn't work for me on the front-end.. No clue why because all of my other Admin bar items appear as expected.

**Comment by imjuniper** [comment]
If you "inspect element" on the admin bar, I assume there's no element with the ID `wp-admin-bar-hestia-nginx-cache-manual-purge`? Also, would it be possible for you to verify in the database that the value is correctly being set? In the `wp_options` table, there should be a row with the `option_name` set to `hestia-nginx-cache`. It contains a serialized array, which you can unserialize [here](https://stuff.jakobbouchard.dev/unserialize.php). The `show_adminbar_button` value should be set to `1`.

**Comment by chriscapisce** [comment]
Indeed, there is no ID with `wp-admin-bar-hestia-nginx-cache-manual-purge`. Also, I checked the `show_adminbar_button` and it's set to `1`, `[show_adminbar_button] => 1.` Any other thoughts on this? I'm using HestiaCP v1.6.10, Wordpress 6.0.3 with the latest version of your plugin, 2.1.4.

**Comment by imjuniper** [comment]
in theory, the only other reason it shouldn't show is if the plugin isn't configured, aka the `access_key` and `secret_key` values aren't set. I doubt it's a Hestia issue though honestly, it's more than likely that it's the plugin or something else in WordPress.

[This part](https://github.com/jakobbouchard/hestia-nginx-cache/blob/develop/hestia-nginx-cache.php#L69-L71) checks if the plugin is configured, while [this one](https://github.com/jakobbouchard/hestia-nginx-cache/blob/develop/includes/admin.php#L35-L37) adds the action to show the button.

**Comment by chriscapisce** [comment]
Yes, it's strange since the plugin works perfectly fine. Incl. the `Clear Cache` button in the Admin bar on the backend. I'm positive that I filled out the `access_key` and `secret_key` correctly. I cleared out all caches and disabled all other plugins. Still no success..

**Comment by imjuniper** [comment]
Hmmm, I actually just noticed that I don't see it in the frontend either. I think I might need to specify that it should appear in the frontend too... I'll look into the WordPress developer reference!

**Comment by chriscapisce** [comment]
Thanks for the solution.
