### ISSUE TITLE
Number appearing on page

### ISSUE THREAD

**Issue by AlecRust** [jakobbouchard/hestia-nginx-cache#15]
I assume since the latest release, when logged in, I'm seeing a number off to the left on all pages 🙂 

![image](https://user-images.githubusercontent.com/247634/199550218-38cee3f2-e63c-449f-9620-fdb64ed0edeb.png)

This appears to be in the HTML:

```html
<span id="hestia-nginx-cache-purge-wp-nonce" class="hidden">1580391665</span>
```

Looks like your plugin is relying on the `.hidden` class existing? It doesn't exist in my case.

**Comment by jaapmarcus** [comment]
Yes...

https://github.com/jakobbouchard/hestia-nginx-cache/blob/09fdce32ad394ba774fee486779f0886650f6c40/includes/admin.php#L230-L235

**Comment by imjuniper** [comment]
whoops it exists in the admin, but not the frontend I guess. I'll fix that later today!

**Comment by imjuniper** [comment]
I fixed it, I hide the nonce manually now :)
