### ISSUE TITLE
[Feature] Hide api key in wp-admin

### ISSUE THREAD

**Issue by jaapmarcus** [jakobbouchard/hestia-nginx-cache#2]
Currently if Wordpress / plugin is hacked or an unauthorised user is able to view the admin they will have access to the api key of the server.

Probably hide the api key on default or even better encrypt the api key by default

**Comment by imjuniper** [comment]
Hmm, I've never encrypted in a database before. Only used stuff like `password_hash`, which wouldn't work in this situation. How would you propose I go about this? Hiding the API key from the admin would be pretty easy though and I'll do that for now.

**Comment by jaapmarcus** [comment]
https://www.geeksforgeeks.org/how-to-encrypt-and-decrypt-a-php-string/

For example

**Comment by imjuniper** [comment]
I just made it so that the password is not shown in the frontend anymore, but I'll try to encrypt it for the 1.2.0 release. I'll release the 1.1.0 either later tonight or tomorrow, I don't have access to my SVN right now.

**Comment by imjuniper** [comment]
Just hiding it from the admin is good for now. It seems most plugins are doing it this way anyway.
