### ISSUE TITLE
The Hestia Nginx Cache was purged successfully not show in Page Site

### ISSUE THREAD

**Issue by maisondasilva** [jakobbouchard/hestia-nginx-cache#26]
I noticed that when clearing the cache in the WordPress admin it appears The Hestia Nginx Cache was purged successfully. However, if I clean it by visiting the website, the message does not appear!

Admin:

![image](https://github.com/jakobbouchard/hestia-nginx-cache/assets/11423362/55a4e3d3-f3b2-4e20-b987-345dd064dacd)

Site:

![image](https://github.com/jakobbouchard/hestia-nginx-cache/assets/11423362/084ddde3-bbe4-4d8c-b836-4021e669dc2c)

https://wordpress.org/support/topic/the-hestia-nginx-cache-was-purged-successfully-not-show-in-page-site/#new-topic-0

**Comment by jaapmarcus** [comment]
There are exactly 2 “bugs”

The Ajax call is not working at all…
https://github.com/jakobbouchard/hestia-nginx-cache/pull/27
The “Admin notice” doesn’t show..
The first bug is easy to patch…

2nd one is bit harder it currently checks if the div / element exists and if not it return / cancels the following step..

**Comment by imjuniper** [comment]
Fixed in next release

**Comment by maisondasilva** [comment]
When cleaning cache in the page main on the website instead of wp admin, no message is displayed!

![image](https://github.com/jakobbouchard/hestia-nginx-cache/assets/11423362/e813cc6b-71ed-4955-824d-d4065b56bfc0)

**Comment by jaapmarcus** [comment]
It should show like:
<img width="1709" alt="Screenshot 2024-02-17 at 16 13 03" src="https://github.com/jakobbouchard/hestia-nginx-cache/assets/9754650/87348f90-635e-41a8-8ada-19a4c5cdddad">

Make sure to clear your browser cache first

**Comment by imjuniper** [comment]
It also didn't work in 2.2.4, but 2.2.5 works!

**Comment by maisondasilva** [comment]
@jaapmarcus @jakobbouchard problem fix cache Cloudflare

![image](https://github.com/jakobbouchard/hestia-nginx-cache/assets/11423362/250bf501-0969-43e1-9586-df85d24f5332)
