### ISSUE TITLE
The page cache was not detected, but the server response time is OK

### ISSUE THREAD

**Issue by maisondasilva** [jakobbouchard/hestia-nginx-cache#34]
I receive the warning below on Wordpress, would it be possible for Hestia Cache to add this header or something like that?

Page caching increases your site's speed and performance by saving and serving static pages instead of calling a page every time a user visits.

Page caching is detected by looking for an active page caching plugin, as well as making three requests to the home page and looking for one or more of the following HTTP client cache response headers:

cache-control, expirations, age, last-modified, etag, x-cache-enabled, x-cache-disabled, x-srcache-store-status, x-srcache-fetch-status.
  The average server response time was 62 milliseconds. This is less than the recommended threshold of 600 milliseconds.
  No client cache response headers were detected.
  A page cache plugin was not detected.

Learn more about page caching (open in a new tab)
https://developer.wordpress.org/advanced-administration/performance/optimization/#Caching

and

You must use a persistent object cache

A persistent object cache makes your site's database more efficient, resulting in faster load times because WordPress can retrieve your site's content and settings much more quickly.

Your hosting provider can tell you whether persistent object caching can be enabled on your site. Your host appears to support the following object caching services: APCu.

Learn more about persistent object caching.(open in new tab)
https://developer.wordpress.org/advanced-administration/performance/optimization/#persistent-object-cache

**Comment by maisondasilva** [comment]
@jakobbouchard @jaapmarcus

**Comment by jaapmarcus** [comment]
Caching is done with Nginx and not with this plugin so we can't add it...

It is still smart to use features like redis cache it will still help a lot ...

Hestia adds by default x-fastcgi-cache: xxx

**Comment by maisondasilva** [comment]
Thanks for the heads up, closing!
