### ISSUE TITLE
not working with apache

### ISSUE THREAD

**Issue by hamudev** [jakobbouchard/hestia-nginx-cache#40]
![image](https://github.com/user-attachments/assets/afea018b-95b5-48e3-a1fb-6ab690dae845)
![image](https://github.com/user-attachments/assets/efb5bc65-7f83-4639-b4c1-62ef6e8efcc2)
![image](https://github.com/user-attachments/assets/22d00425-6ab8-4a1f-b805-cd9436d941ce)

hi, i tried to setup this plugin with apache server but seem like it not working, i also already setup the api key and change proxy template to caching but the cache could not be purged.

**Comment by jaapmarcus** [comment]
If you run Hestia behind Cloudflare try using localhost

**Comment by hamudev** [comment]
thank you for your respond, btw how to do that? @jaapmarcus

**Comment by hamudev** [comment]
everything was fine if im using nginx server. today i have setup new apache server but the cache not purge like image i have attach above.

**Comment by jaapmarcus** [comment]
Use 127.0.0.1 instead of hostname

**Comment by hamudev** [comment]
![image](https://github.com/user-attachments/assets/727c7d0e-5e09-4c5a-9542-a08e5693cf42)
the result was same.

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/auth.log

**Comment by hamudev** [comment]
![image](https://github.com/user-attachments/assets/3a8e1bdd-ad19-45d0-91d3-07c8b427e86a)
here my auth.log

**Comment by hamudev** [comment]
btw if im using purge NGINX Cache button it working . 
![image](https://github.com/user-attachments/assets/289b1b37-94d6-4461-9ce0-c80862c8ab0c)

**Comment by jaapmarcus** [comment]
Add allow-all to the ip whitelist in server settings and it should work fine

**Comment by hamudev** [comment]
im really sorry. may i know how to do that? or is it like this? 
![image](https://github.com/user-attachments/assets/62c88224-c5d1-4456-bb25-b2e1ccae593c)

**Comment by jaapmarcus** [comment]
No in server settings 

<img width="742" alt="Screenshot 2024-07-22 at 11 48 02" src="https://github.com/user-attachments/assets/9fd966b5-ddc0-46cf-ba3a-261ce6b55504">

**Comment by hamudev** [comment]
yeah i did it and its working well. thank you very much for your help and time. 
![image](https://github.com/user-attachments/assets/7ebbd292-7376-4822-abc0-ccfc267959f2)
