### ISSUE TITLE
Port and IP?

### ISSUE THREAD

**Issue by Gunstra** [jakobbouchard/hestia-nginx-cache#41]
The create api key in Hestia doesn't show the port needed for this plugin. Also the api key fields don't ask for an ip but that is a given.

**Comment by jaapmarcus** [comment]
For the port number you can supply the same port number as you connect to Hestia 

For example: panel.mydomain.com:2083 You need to supply 2083 as port number

For IP you don't need to supply any ip when you create an api key how ever you need to enter your server ip in Settings -> Securtity -> White listed ips

**Comment by Gunstra** [comment]
I have done that and I get this when purging:

[image: image.png]

---
Brent D.
***@***.***

**Comment by jaapmarcus** [comment]
Image doesn't work
