### ISSUE TITLE
You should use a persistent object cache and Page caching was not detected, but server response time is OK

### ISSUE THREAD

**Issue by maisondasilva** [jakobbouchard/hestia-nginx-cache#43]
Would it be possible to include the options below in the plugin so that in WordPress performance it will notice that there is an active cache and not warn the messages below?

In site-health.php

You should use a persistent object cache
A persistent object cache makes your site's database more efficient, resulting in faster load times
because WordPress can retrieve your site's content and settings much more quickly.

Your hosting provider can tell you if a persistent object cache can be enabled on your site.

Learn more about persistent object caching.
https://developer.wordpress.org/advanced-administration/performance/optimization/#persistent-object-cache

Page caching was not detected, but server response time is OK
Page caching increases the speed and performance of your site by saving and serving static pages instead of calling a
page every time a user visits.

Page caching is detected by looking for an active page caching plugin, as well as by making three requests to the home page and looking for one or more of the following HTTP client caching response headers:

cache-control, expires, age, last-modified, etag, x-cache-enabled, x-cache-disabled, x-srcache-store-status, x-srcache-fetch-status.

The average server response time was 37 milliseconds. This is less than the recommended threshold of 600 milliseconds.
No client caching response headers were detected.
A page caching plugin was not detected.
Learn more about page caching
https://developer.wordpress.org/advanced-administration/performance/optimization/#caching

@jakobbouchard @jaapmarcus

**Comment by jaapmarcus** [comment]
https://github.com/jakobbouchard/hestia-nginx-cache/issues/34

Hestia need to change it is not managed by this plugin...

**Comment by maisondasilva** [comment]
Sorry, I forgot I asked about it.
