### ISSUE TITLE
Add a toggle for the admin bar button and shorten its label

### ISSUE THREAD

**Issue by imjuniper** [jakobbouchard/hestia-nginx-cache#5]
> This plugin is permanent items in the Admin Bar can be a bit annoying, and “Purge Hestia Nginx Cache” is quite long. It would be nice of there was an option to disable this Admin Bar item in the plugin settings [...].

Feedback from the [WordPress plugin directory](https://wordpress.org/support/topic/how-can-i-test-it-2/).

**Comment by chriscapisce** [comment]
As an alternative / addition to disabling the admin bar item: It would be great to be able to rename it through the settings with a textfield.

**Comment by imjuniper** [comment]
Oh yeah, sure thing. That won't be hard to implement.

**Comment by chriscapisce** [comment]
Awesome, thanks a lot!
