### ISSUE TITLE
Add some status/connection info somewhere

### ISSUE THREAD

**Issue by imjuniper** [jakobbouchard/hestia-nginx-cache#7]
Add some information about the plugin's status/connection either in the plugin's settings or in the Info tab in the Site Health page.

Info to add:

- Version
- Status (Connected/Not connected)
- Host
- Port

Perhaps even add an error to the status when it can't connect to Hestia.

Feedback from the [WordPress plugin directory](https://wordpress.org/support/topic/how-can-i-test-it-2/).

**Comment by imjuniper** [comment]
@jaapmarcus Is there a way I could test the API credentials other than clearing the cache? Something like a ping? That way I could add connection status and warnings to the Site Health page, as well as warn when the settings are wrong.

**Comment by jaapmarcus** [comment]
No currently not...

**Comment by imjuniper** [comment]
Since I no longer work in web dev, I probably won't be adding these feature in the near future or at all. I still use the plugin for some websites, but I won't add features
